# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 08:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='\u6587\u7ae0\u6807\u9898')),
                ('desc', models.CharField(max_length=50, verbose_name='\u6587\u7ae0\u63cf\u8ff0')),
                ('content', models.TextField(verbose_name='\u6587\u7ae0\u5185\u5bb9')),
                ('love_count', models.IntegerField(default=0, verbose_name='\u559c\u6b22\u6570')),
                ('click_count', models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6b21\u6570')),
                ('date_publish', models.DateTimeField(auto_now_add=True, verbose_name='\u53d1\u5e03\u65f6\u95f4')),
            ],
            options={
                'ordering': ['-date_publish'],
                'verbose_name': '\u6587\u7ae0',
                'verbose_name_plural': '\u6587\u7ae0',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('number', models.IntegerField(default=999, verbose_name='\u8bbf\u95ee\u91cf')),
            ],
            options={
                'ordering': ['number', 'id'],
                'verbose_name': '\u5206\u7c7b',
                'verbose_name_plural': '\u5206\u7c7b',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u56fe\u7247\u540d\u79f0')),
                ('imgpath', models.CharField(max_length=300, verbose_name='\u56fe\u7247\u8def\u5f84')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u53d1\u5e03\u8005\u540d\u79f0')),
                ('intro', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Image')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u8005',
                'verbose_name_plural': '\u53d1\u5e03\u8005',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u6765\u6e90\u7c7b\u522b')),
            ],
            options={
                'verbose_name': '\u53d1\u5e03\u8005\u7c7b\u522b',
                'verbose_name_plural': '\u53d1\u5e03\u8005\u7c7b\u522b',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='\u6807\u7b7e\u540d\u79f0')),
                ('number', models.IntegerField(default=0, verbose_name='\u8bbf\u95ee\u91cf')),
            ],
            options={
                'verbose_name': '\u6807\u7b7e',
                'verbose_name_plural': '\u6807\u7b7e',
            },
        ),
        migrations.AddField(
            model_name='publisher',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Source', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcweb.Category', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AddField(
            model_name='article',
            name='cover',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Image', verbose_name='\u5c01\u9762\u56fe\u7247'),
        ),
        migrations.AddField(
            model_name='article',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Publisher', verbose_name='\u53d1\u5e03\u8005'),
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='dcweb.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
