# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-16 11:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='number',
            field=models.IntegerField(default=0, verbose_name='\u8bbf\u95ee\u91cf'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dcweb.Image'),
        ),
    ]
