# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0002_auto_20180116_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgpath',
        ),
        migrations.AddField(
            model_name='image',
            name='img',
            field=models.ImageField(blank=True, upload_to='img', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='dcweb.Tag', verbose_name='\u6807\u7b7e'),
        ),
    ]
