# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 01:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0003_auto_20180117_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='cover',
        ),
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
