# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 12:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dcweb', '0004_auto_20180118_0930'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u5386\u53f2\u8bb0\u5f55',
                'verbose_name_plural': '\u6d4f\u89c8\u5386\u53f2',
            },
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u63a8\u8350',
                'verbose_name_plural': '\u63a8\u8350',
            },
        ),
        migrations.CreateModel(
            name='Star',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '\u5173\u6ce8',
                'verbose_name_plural': '\u5173\u6ce8',
            },
        ),
        migrations.CreateModel(
            name='UserNormal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.BooleanField(default=True, verbose_name='\u6027\u522b')),
                ('age', models.IntegerField(blank=True, default=18, verbose_name='\u5e74\u9f84')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='\u7535\u8bdd')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='\u90ae\u7bb1')),
                ('desc', models.CharField(max_length=300, verbose_name='\u7b80\u4ecb')),
                ('img', models.ImageField(upload_to='user', verbose_name='\u5934\u50cf')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='art', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pub', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
        migrations.AddField(
            model_name='star',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Publisher'),
        ),
        migrations.AddField(
            model_name='star',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.UserNormal'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Article'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.UserNormal'),
        ),
        migrations.AddField(
            model_name='history',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.Article'),
        ),
        migrations.AddField(
            model_name='history',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dcweb.UserNormal'),
        ),
    ]
