# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0008_auto_20180119_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='time',
            field=models.DateTimeField(auto_now=True, verbose_name='\u65f6\u95f4'),
        ),
    ]
