# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-19 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0009_history_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernormal',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='user', verbose_name='\u5934\u50cf'),
        ),
    ]
