# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-08 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0013_auto_20180205_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tag_mark',
            field=models.BooleanField(default=False, verbose_name='\u6807\u7b7e\u6807\u8bb0'),
        ),
    ]
