# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-27 04:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dcweb', '0015_love'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='pub', verbose_name='\u56fe\u7247\u8def\u5f84'),
        ),
    ]
